### ISSUE TITLE
View Full is broken

### ISSUE THREAD

**Issue by harryttd** [ovity/octotree#1104]
### Description
I am hitting the view full button on a PR. The window just endlessly loads.

### Environment (if bug)

* Octotree version: v7.2.4
* Browser & version: Chrome Version 96.0.4664.55 (Official Build) (x86_64)
* OS & version: Mac Big Sur 11.6
* Console error log below this line
```
DevTools failed to load source map: Could not load content for chrome-extension://bkhaagjahfmjljalopjnoealnfndnagc/browser-polyfill.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
```
In the "background extension" chrome devtools window:
```
69Unchecked runtime.lastError: Cannot access contents of the page. Extension manifest must request permission to access the respective host.
_generated_background_page.html:1 Unchecked runtime.lastError: The extensions gallery cannot be scripted.
_generated_background_page.html:1 Unchecked runtime.lastError: The extensions gallery cannot be scripted.
_generated_background_page.html:1 Unchecked runtime.lastError: The extensions gallery cannot be scripted.
6Unchecked runtime.lastError: Cannot access a chrome:// URL
87Unchecked runtime.lastError: The tab was closed.
browser-polyfill.js:1109 Returning a Promise is the preferred way to send a reply from an onMessage/onMessageExternal listener, as the sendResponse will be removed from the specs (See https://developer.mozilla.org/docs/Mozilla/Add-ons/WebExtensions/API/runtime/onMessage) Error
    at wrappedSendResponse (chrome-extension://bkhaagjahfmjljalopjnoealnfndnagc/browser-polyfill.js:1109:65)
    at r (chrome-extension://bkhaagjahfmjljalopjnoealnfndnagc/background.js:1:9533)
wrappedSendResponse @ browser-polyfill.js:1109
DevTools failed to load source map: Could not load content for chrome-extension://bkhaagjahfmjljalopjnoealnfndnagc/browser-polyfill.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
```

**Comment by danhgit** [comment]
Thanks for reporting. GitHub has changed the PR page and added the "expand all" button to view the whole file. That change also broke our view full button 😅. Anyway, the new "expand all" fulfills the need, so we removed the "view full" button in v7.2.5 which should be available shortly. 

<img width="202" alt="expand" src="https://user-images.githubusercontent.com/38257704/144951116-106bdecd-06ed-4593-ad62-b4e6f0965eef.png">

**Comment by harryttd** [comment]
Thanks!
