### ISSUE TITLE
Tabs are not working and no option in settings as described in docs

### ISSUE THREAD

**Issue by tbusillo** [ovity/octotree#1174]
### Description

- The website and extension store listing mentions "tabs" as being a pro feature
- This feature is not working in either Chrome or Firefox (MacOS)
- Double-clicking on a file in the file-tree just navigates in the current _browser_ tab 
- The docs also mention, "Note: you can disable this feature by unchecking "Enable multi-tab" in the Settings screen". There is no option in the settings to enable or disable multi-tab (screenshot below of options visible). 

![CleanShot 2024-03-23 at 10 40 39@2x](https://github.com/ovity/octotree/assets/1016306/3c8d4b0d-3849-4a78-a43f-44fb5637a016)

### Environment (if bug)

* Octotree version: v7.12.1
* Browser & version: Version 123.0.6312.59 (Official Build) (arm64)
* OS & version: MacOS 14.4
* Console error log below this line

It seems to be tied to a selector not being found/being null not being handled properly (transpiled code is along lines of `r=!t.classList.contains("Overlay--hidden")`, with `t` being `null`. 

The below errors are seen in console consistently:

**Chrome**

```sh
content.js:2 Uncaught TypeError: Cannot read properties of null (reading 'classList')
    at Yi.MutationObserver.observe.childList (content.js:2:546093)
Yi.MutationObserver.observe.childList @ content.js:2
10:47:21.893 content.js:2 Uncaught TypeError: Cannot read properties of null (reading 'classList')
    at Yi.MutationObserver.observe.childList (content.js:2:546093)
Yi.MutationObserver.observe.childList @ content.js:2
10:47:22.013 content.js:2 Uncaught TypeError: Cannot read properties of null (reading 'classList')
    at Yi.MutationObserver.observe.childList (content.js:2:546093)
Yi.MutationObserver.observe.childList @ content.js:2
10:47:22.019 content.js:2 Uncaught TypeError: Cannot read properties of null (reading 'classList')
    at Yi.MutationObserver.observe.childList (content.js:2:546093)
Yi.MutationObserver.observe.childList @ content.js:2
10:47:22.045 analytics-client.js:47 
        
        
       POST https://collector.github.com/github/collect net::ERR_CONNECTION_REFUSED
```

**Firefox**
```sh
TypeError: t is null
2 [content.js:2:546148](moz-extension://aa1633fa-cef9-4a8c-93c4-ebf238c54382/content.js)
    Xi moz-extension://aa1633fa-cef9-4a8c-93c4-ebf238c54382/content.js:2
    (Async: MutationCallback)
    Xi moz-extension://aa1633fa-cef9-4a8c-93c4-ebf238c54382/content.js:2
    InterpretGeneratorResume self-hosted:1465
    AsyncFunctionNext self-hosted:852
    (Async: async)
    <anonymous> moz-extension://aa1633fa-cef9-4a8c-93c4-ebf238c54382/content.js:2
    D moz-extension://aa1633fa-cef9-4a8c-93c4-ebf238c54382/content.js:2
    <anonymous> moz-extension://aa1633fa-cef9-4a8c-93c4-ebf238c54382/content.js:2
    InterpretGeneratorResume self-hosted:1465
    AsyncFunctionNext self-hosted:852
    (Async: async)
    U moz-extension://aa1633fa-cef9-4a8c-93c4-ebf238c54382/content.js:2
    <anonymous> moz-extension://aa1633fa-cef9-4a8c-93c4-ebf238c54382/content.js:2
    c moz-extension://aa1633fa-cef9-4a8c-93c4-ebf238c54382/content.js:2
    d moz-extension://aa1633fa-cef9-4a8c-93c4-ebf238c54382/content.js:2
    (Async: setTimeout handler)
    o moz-extension://aa1633fa-cef9-4a8c-93c4-ebf238c54382/content.js:2
    l moz-extension://aa1633fa-cef9-4a8c-93c4-ebf238c54382/content.js:2
    fireWith moz-extension://aa1633fa-cef9-4a8c-93c4-ebf238c54382/content.js:2
    fire moz-extension://aa1633fa-cef9-4a8c-93c4-ebf238c54382/content.js:2
    l moz-extension://aa1633fa-cef9-4a8c-93c4-ebf238c54382/content.js:2
    fireWith moz-extension://aa1633fa-cef9-4a8c-93c4-ebf238c54382/content.js:2
    ready moz-extension://aa1633fa-cef9-4a8c-93c4-ebf238c54382/content.js:2
    V moz-extension://aa1633fa-cef9-4a8c-93c4-ebf238c54382/content.js:2
    (Async: EventListener.handleEvent)
    755 moz-extension://aa1633fa-cef9-4a8c-93c4-ebf238c54382/content.js:2
    755 moz-extension://aa1633fa-cef9-4a8c-93c4-ebf238c54382/content.js:2
    755 moz-extension://aa1633fa-cef9-4a8c-93c4-ebf238c54382/content.js:2
    i moz-extension://aa1633fa-cef9-4a8c-93c4-ebf238c54382/content.js:2
    193 moz-extension://aa1633fa-cef9-4a8c-93c4-ebf238c54382/content.js:2
    i moz-extension://aa1633fa-cef9-4a8c-93c4-ebf238c54382/content.js:2
    <anonymous> moz-extension://aa1633fa-cef9-4a8c-93c4-ebf238c54382/content.js:2
    <anonymous> moz-extension://aa1633fa-cef9-4a8c-93c4-ebf238c54382/content.js:2
    <anonymous> moz-extension://aa1633fa-cef9-4a8c-93c4-ebf238c54382/content.js:2
    inject resource://gre/modules/ExtensionContent.sys.mjs:583
    AsyncFunctionNext self-hosted:852
    injectScriptSync moz-extension://d91ccbc2-e8e4-4de5-960f-8c6b30dcbfb7/build/prepareInjection.js:1
    <anonymous> moz-extension://d91ccbc2-e8e4-4de5-960f-8c6b30dcbfb7/build/prepareInjection.js:1
    <anonymous> moz-extension://d91ccbc2-e8e4-4de5-960f-8c6b30dcbfb7/build/prepareInjection.js:1
    <anonymous> moz-extension://d91ccbc2-e8e4-4de5-960f-8c6b30dcbfb7/build/prepareInjection.js:1
    inject resource://gre/modules/ExtensionContent.sys.mjs:583
    AsyncFunctionNext self-hosted:852
```

**Comment by danhgit** [comment]
Hi, we temporarily disabled this feature because GitHub had introduced some changes that completely broke it as well as the page (even when it's disabled). We haven't been able to make it work yet. To avoid misleading people, we will remove mention of it from our website until we add it back. Thanks for pointing this out.

**Comment by danhgit** [comment]
We have decided to not supporting this feature. It was one of the most complicated features to build, and yet it is was very brittle due to the tight coupling with GitHub UI & DOM. GitHub UI & DOM have changed so much since, that if we want to have this feature now, we basically have to build it again from scratch. Yet, reliability will still be an issue.
