### ISSUE TITLE
macos mojave build error

### ISSUE THREAD

**Issue by xiadingZ** [ovity/octotree#587]
### Description
If this is a bug, provide as much information as you can to help reproduce the issue.

### Environment (if bug)

* Octotree version: 2.5.1
* Browser & version: safari 12
* OS & version: macos mojave public beta 10.14.3
* Screenshot, if any (drag an image here)
* Console error log below this line

used command:

```
brew install npm
npm install gulp
gulp safari
```

error
```
fs.js:25
'use strict';
^

ReferenceError: internalBinding is not defined
    at fs.js:25:1
    at req_ (/Users/xd/Downloads/octotree-2.5.1/node_modules/natives/index.js:140:5)
    at Object.req [as require] (/Users/xd/Downloads/octotree-2.5.1/node_modules/natives/index.js:54:10)
    at Object.<anonymous> (/Users/xd/Downloads/octotree-2.5.1/node_modules/graceful-fs/fs.js:1:99)
    at Module._compile (internal/modules/cjs/loader.js:723:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:734:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:659:17)
```

**Comment by hamsternik** [comment]
Again, I catched a similar error

``` sh
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'gulp-util'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/hamsternik/Developer/github/octotree/gulpfile.js:2:15)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
```

**Comment by coreice** [comment]
I was also experiencing this issue, but running `yarn install` & `yarn build` before running `gulp safari` did the trick for me.

**Comment by buunguyen** [comment]
Yeah, should run via npm or yarn, not gulp directly.
