### ISSUE TITLE
Fail to build

### ISSUE THREAD

**Issue by BigTony666** [ovity/octotree#627]
### Description
Follow the instruction to install and fail to build.

1.  `npm i`
2. `npm run build`

Result:

```sh
> octotree@2.5.5 build /Users/bigtony/playground/octotree
> gulp build

internal/util/inspect.js:31
const types = internalBinding('types');
              ^

ReferenceError: internalBinding is not defined
    at internal/util/inspect.js:31:15
    at req_ (/Users/bigtony/playground/octotree/node_modules/natives/index.js:140:5)
    at require (/Users/bigtony/playground/octotree/node_modules/natives/index.js:113:12)
    at util.js:25:21
    at req_ (/Users/bigtony/playground/octotree/node_modules/natives/index.js:140:5)
    at require (/Users/bigtony/playground/octotree/node_modules/natives/index.js:113:12)
    at fs.js:42:21
    at req_ (/Users/bigtony/playground/octotree/node_modules/natives/index.js:140:5)
    at Object.req [as require] (/Users/bigtony/playground/octotree/node_modules/natives/index.js:54:10)
    at Object.<anonymous> (/Users/bigtony/playground/octotree/node_modules/graceful-fs/fs.js:1:99)
```

### Environment (if bug)

* Octotree version: 2.5.5
* Browser & version: Chrome
* OS & version: MacOS

**Comment by BigTony666** [comment]
Not sure why this happens, but fixed the problem after google.

Solution:
Install this package
```sh
$ npm i natives@1.1.6
```
