### ISSUE TITLE
ReferenceError: primordials is not defined

### ISSUE THREAD

**Issue by sguillia** [ovity/octotree#951]
Hi

Octotree doesn't build

Steps to reproduce

- git clone https://github.com/ovity/octotree/
- cd octotree
- npm install
- npm run dist

```
> octotree@3.0.10 dist /home/user/Applications/github/octotree
> gulp dist --production

fs.js:27
const { Math, Object } = primordials;
                         ^

ReferenceError: primordials is not defined
    at fs.js:27:26
    at req_ (/home/user/Applications/github/octotree/node_modules/natives/index.js:140:5)
    at Object.req [as require] (/home/user/Applications/github/octotree/node_modules/natives/index.js:54:10)
    at Object.<anonymous> (/home/user/Applications/github/octotree/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at require (internal/modules/cjs/helpers.js:16:16)
npm ERR! code ELIFECYCLE
```

Commit 6130a848ca2e410dfaf0c774529e55daa4d5f9b0

Linux 4.15.0-96-generic # 97~16.04.1-Ubuntu SMP Wed Apr 1 03:03:31 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by buunguyen** [comment]
Hi, please try Node 10.
